Testing network connectivity windows
ans-group/docs.ukfast.co.uk pull request #698
Opened 2020-09-04 14:01 UTC by danielc96

2020-09-09 16:16 UTC, CountBacula requested changes
Few typos and readability issues but otherwise it's good.

2020-09-09 16:16 UTC, CountBacula commented on source/operatingsystems/windows/mssql/mssql_remote.md
> +## Connecting to MSSQL Instance remotely
Page is missing a top level header, "#"

2020-09-09 16:16 UTC, CountBacula commented on source/operatingsystems/windows/mssql/mssql_remote.md
> +In order to connect to a MSSQL instance from a remote source, The following is required;
":" vs ";" + other instances of this throughout the doc.

2020-09-09 16:16 UTC, CountBacula commented on source/operatingsystems/windows/networking/testing-and-troubleshooting-network-connectivity.md
> +To test general outbound connectivity from your server over a specific port. The following Powershell command is extremely useful;
":"s vs ";"s

2020-09-09 16:16 UTC, CountBacula commented on source/operatingsystems/windows/networking/testing-and-troubleshooting-network-connectivity.md
> +```
PowerShell syntax highlighting if you want to.

2020-09-09 16:16 UTC, CountBacula commented on source/operatingsystems/windows/networking/testing-and-troubleshooting-network-connectivity.md
> +```
Add PowerShell alternative?

2020-09-09 16:16 UTC, CountBacula commented on source/operatingsystems/windows/networking/testing-and-troubleshooting-network-connectivity.md
> +Dependent upon on whether or not your server resides behind a dedicated or shared firewall, The following documentation will guide you through securely opening ports on your firewall;
Just needs a reword for readability.

2020-09-09 16:16 UTC, CountBacula commented on source/operatingsystems/windows/networking/testing-and-troubleshooting-network-connectivity.md
> +Paired with the hostname "portquiz.net", which is a service in which is publicly accessible on all ports, we are able to gauge as to whether or not the port is open outbound through the firewall and
Reword for readability

2020-09-09 16:16 UTC, CountBacula commented on source/operatingsystems/windows/networking/testing-and-troubleshooting-network-connectivity.md
> +**Wireshark** ;
":"

2020-09-09 16:16 UTC, CountBacula commented on source/operatingsystems/windows/networking/testing-and-troubleshooting-network-connectivity.md
> +**Powershell;**
":"

2020-09-09 16:16 UTC, CountBacula commented on source/operatingsystems/windows/networking/testing-and-troubleshooting-network-connectivity.md
> +$Listener.Stop();
Add codeblocks here?

2020-09-09 16:16 UTC, CountBacula commented on source/operatingsystems/windows/networking/testing-and-troubleshooting-network-connectivity.md
> +```
Use PowerShell for all of these steps rather than swapping between this and CMD?

2022-10-19 08:18 UTC, miff2000 commented
I'm closing this. The new content has been added in PR #1004. Any other updates can be done via new PRs

2022-10-19 08:18 UTC, closed without merging